openapi: 3.1.0
info:
  title: Frontend-Backend API
  description: API contract between Frontend (React) and Backend (Express)
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
  - url: https://api.example.com/v1
    description: Production server

tags:
  - name: Health
    description: Health check endpoints
  - name: Users
    description: User management endpoints
  - name: Chat
    description: Chat endpoints
  - name: Documents
    description: Document management endpoints

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Returns the health status of the backend service
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time

  /chat/stream:
    post:
      tags:
        - Chat
      summary: Stream chat response
      description: Send a chat message and stream the AI response via SSE
      operationId: chatStream
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - sessionId
              properties:
                message:
                  type: string
                  description: User's chat message
                  example: "What is Efsora?"
                  maxLength: 4000
                sessionId:
                  type: string
                  format: uuid
                  description: Client-generated session UUID
                  example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: SSE stream of chat response chunks
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Event data chunks
                example: "data: Hello\n\ndata: World\n\n"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Session does not belong to user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /chat/sessions/{sessionId}/messages:
    get:
      tags:
        - Chat
      summary: Get chat history
      description: Retrieve all messages for a chat session
      operationId: getChatHistory
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Session UUID
          example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: List of chat messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        role:
                          type: string
                          enum: [user, assistant]
                        content:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Session does not belong to user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Session not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /documents/get-upload-url:
    post:
      tags:
        - Documents
      summary: Generate upload URL
      description: Generate a pre-signed URL for uploading a document to S3
      operationId: generateUploadUrl
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateUploadUrlRequest"
      responses:
        "200":
          description: Pre-signed URL generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerateUploadUrlResponse"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - User does not have access to the project
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /documents/embed:
    post:
      tags:
        - Documents
      summary: Embed document
      description: |
        Embed a document from S3 into the vector database.
        Returns progress updates via Server-Sent Events (SSE).
      operationId: embedDocument
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmbedDocumentRequest"
      responses:
        "200":
          description: SSE stream of embedding progress events
          content:
            text/event-stream:
              schema:
                type: string
                description: |
                  Server-Sent Event data containing EmbedDocumentProgressEvent JSON.
                  Each event is formatted as: data: {json}\n\n
                example: 'data: {"stage":"embedding","progress_percent":45,"message":"Generating embeddings...","chunks_processed":5,"total_chunks":12}\n\n'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - User does not have access to the project
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

    GenerateUploadUrlRequest:
      type: object
      required:
        - fileName
        - fileSize
        - fileType
        - projectId
      properties:
        fileName:
          type: string
          description: Name of the file to upload
          example: "project-proposal.pdf"
          minLength: 1
          maxLength: 255
        fileSize:
          type: integer
          description: File size in bytes
          example: 1048576
          minimum: 1
        fileType:
          type: string
          description: MIME type of the file
          example: "application/pdf"
          pattern: "^[a-z]+/[a-z0-9\\-+.]+$"
        projectId:
          type: integer
          description: ID of the project
          example: 1
          minimum: 1

    GenerateUploadUrlResponse:
      type: object
      required:
        - uploadUrl
        - s3Key
        - expiresIn
      properties:
        uploadUrl:
          type: string
          format: uri
          description: Pre-signed URL for uploading the file to S3
          example: "https://bucket.s3.amazonaws.com/path/to/file?X-Amz-Algorithm=..."
        s3Key:
          type: string
          description: S3 object key where the file will be stored
          example: "documents/1/5/project-proposal.pdf"
        expiresIn:
          type: integer
          description: Number of seconds until the URL expires
          example: 900
          minimum: 1

    EmbedDocumentRequest:
      type: object
      required:
        - s3Key
        - projectId
      properties:
        s3Key:
          type: string
          description: S3 object key of the document to embed
          example: "documents/1/5/quarterly_report.pdf"
          minLength: 1
          maxLength: 1024
        projectId:
          type: integer
          description: Project ID for metadata tracking
          example: 5
          minimum: 1
        collectionName:
          type: string
          description: Weaviate collection name (optional, uses default if not provided)
          example: "EfsoraDocs"
          maxLength: 100

    EmbedDocumentProgressEvent:
      type: object
      required:
        - stage
        - progress_percent
        - message
      properties:
        stage:
          type: string
          enum:
            - downloading
            - loading
            - chunking
            - embedding
            - storing
            - completed
            - error
          description: |
            Current stage of the embedding process:
            - downloading (0-10%): Downloading file from S3
            - loading (10-20%): Loading and parsing document
            - chunking (20-30%): Semantic chunking
            - embedding (30-90%): Generating embeddings
            - storing (90-100%): Storing in Weaviate
            - completed (100%): Done
            - error: Failed with error message
        progress_percent:
          type: integer
          minimum: 0
          maximum: 100
          description: Overall progress percentage
        message:
          type: string
          description: Human-readable status message
        chunks_processed:
          type: integer
          minimum: 0
          default: 0
          description: Number of chunks processed so far
        total_chunks:
          type: integer
          minimum: 0
          default: 0
          description: Total number of chunks to process
        document_id:
          type: string
          description: Document identifier (set on completion)
        error_code:
          type: string
          description: Error code (set on error)

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
