openapi: 3.1.0
info:
  title: Frontend-Backend API
  description: API contract between Frontend (React) and Backend (Express)
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server
  - url: https://api.example.com/v1
    description: Production server

tags:
  - name: Health
    description: Health check endpoints
  - name: Users
    description: User management endpoints
  - name: Chat
    description: Chat endpoints
  - name: Uploads
    description: File upload endpoints

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Returns the health status of the backend service
      operationId: getHealth
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time

  /chat/stream:
    post:
      tags:
        - Chat
      summary: Stream chat response
      description: Send a chat message and stream the AI response via SSE
      operationId: chatStream
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - sessionId
              properties:
                message:
                  type: string
                  description: User's chat message
                  example: "What is Efsora?"
                  maxLength: 4000
                sessionId:
                  type: string
                  format: uuid
                  description: Client-generated session UUID
                  example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: SSE stream of chat response chunks
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Event data chunks
                example: "data: Hello\n\ndata: World\n\n"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Session does not belong to user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /chat/sessions/{sessionId}/messages:
    get:
      tags:
        - Chat
      summary: Get chat history
      description: Retrieve all messages for a chat session
      operationId: getChatHistory
      security:
        - bearerAuth: []
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Session UUID
          example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: List of chat messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        role:
                          type: string
                          enum: [user, assistant]
                        content:
                          type: string
                        createdAt:
                          type: string
                          format: date-time
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - Session does not belong to user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Session not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /uploads/get-upload-url:
    post:
      tags:
        - Uploads
      summary: Get upload URL
      description: Generate a pre-signed upload URL for file uploads
      operationId: getUploadUrl
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fileName
                - fileSize
                - fileType
                - projectId
              properties:
                fileName:
                  type: string
                  description: Name of the file to be uploaded
                  example: "document.pdf"
                fileSize:
                  type: integer
                  description: Size of the file in bytes
                  example: 1024000
                fileType:
                  type: string
                  description: MIME type of the file
                  example: "application/pdf"
                projectId:
                  type: string
                  format: uuid
                  description: Project ID associated with the upload
                  example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: Upload URL generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  uploadUrl:
                    type: string
                    format: uri
                    description: Pre-signed URL for uploading the file
                    example: "https://s3.amazonaws.com/bucket/path?signature=..."
                  expiresIn:
                    type: integer
                    description: URL expiration time in seconds
                    example: 3600
        "400":
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden - User does not have access to project
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Project not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
